//go:build ignore

// gen reads the current quote from every source, keeps each response as
// testdata and writes builtin_gen.go from the bank's, so the shipped set is
// never typed by hand. Run it from the feed directory before a release:
//
//	go run gen.go
//
// With -from it reads the responses already kept in a directory instead of
// asking a source, which rebuilds the shipped set without a request.
package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"time"

	"github.com/karamble/omarchy-omabudget/feed"
)

// files names the response kept for each source.
var files = map[string]string{
	"ecb":         "ecb-daily.xml",
	"frankfurter": "frankfurter.json",
}

func main() {
	from := flag.String("from", "", "read the responses from this directory instead of asking a source")
	out := flag.String("out", ".", "the feed package directory to write into")
	flag.Parse()
	if err := run(*from, *out); err != nil {
		fmt.Fprintln(os.Stderr, "gen:", err)
		os.Exit(1)
	}
}

func run(from, out string) error {
	bodies := map[string][]byte{}
	for _, src := range feed.Sources {
		name, ok := files[src.ID]
		if !ok {
			return fmt.Errorf("no file name for source %s", src.ID)
		}
		var body []byte
		var err error
		if from != "" {
			body, err = os.ReadFile(filepath.Join(from, name))
		} else {
			ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
			body, err = feed.Download(ctx, src)
			cancel()
		}
		if err != nil {
			return err
		}
		bodies[src.ID] = body
	}

	quotes := map[string]feed.Quote{}
	for id, body := range bodies {
		src, _ := feed.Lookup(id)
		q, err := src.Parse(bytes.NewReader(body))
		if err != nil {
			return err
		}
		quotes[id] = q
	}
	// The two are one dataset: a disagreement means one of them changed
	// shape, and nothing should ship until someone has looked.
	ecb, ff := quotes["ecb"], quotes["frankfurter"]
	if ecb.Date != ff.Date || ecb.Base != ff.Base || len(ecb.Rates) != len(ff.Rates) {
		return fmt.Errorf("sources disagree: ecb %s %s with %d rates, frankfurter %s %s with %d rates",
			ecb.Base, ecb.Date, len(ecb.Rates), ff.Base, ff.Date, len(ff.Rates))
	}
	for currency, rate := range ecb.Rates {
		if other, ok := ff.Rates[currency]; !ok || !rate.Equal(other) {
			return fmt.Errorf("sources disagree on %s: ecb %s, frankfurter %s", currency, rate, other)
		}
	}

	if from == "" {
		dir := filepath.Join(out, "testdata")
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
		for id, body := range bodies {
			if err := os.WriteFile(filepath.Join(dir, files[id]), body, 0o644); err != nil {
				return err
			}
		}
	}
	src, err := render(ecb)
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(out, "builtin_gen.go"), src, 0o644)
}

// render writes the quote as Go source.
func render(q feed.Quote) ([]byte, error) {
	currencies := make([]string, 0, len(q.Rates))
	for c := range q.Rates {
		currencies = append(currencies, c)
	}
	sort.Strings(currencies)
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gen.go; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package feed\n\n")
	fmt.Fprintf(&b, "import %q\n\n", "github.com/karamble/omarchy-omabudget/money")
	fmt.Fprintf(&b, "// Builtin is the quote shipped with the binary: one %s in each currency,\n", q.Base)
	fmt.Fprintf(&b, "// as the %s published it on %s.\n", feed.ECB.Name, q.Date)
	fmt.Fprintf(&b, "var Builtin = Quote{\n\tBase: %q,\n\tDate: %q,\n\tRates: map[string]money.Rate{\n", q.Base, q.Date)
	for _, c := range currencies {
		fmt.Fprintf(&b, "\t\t%q: %q,\n", c, q.Rates[c])
	}
	fmt.Fprintf(&b, "\t},\n}\n")
	return format.Source(b.Bytes())
}
